### ISSUE TITLE
VPS重启完测试页面就打不开，要重装，不知是不是默认安装到/temp里头？

### ISSUE THREAD

**Issue by netwlb** [BigMangos/speedtest-go-script#1]
VPS重启完测试页面就打不开，要重装，不知是不是默认安装到/temp里头？

**Comment by bigmangos** [comment]
在脚本中增加了 start 和 stop，系统重启后可以再次执行脚本中的 start 就可以了

**Comment by netwlb** [comment]
是不是要重装脚本才有start选项？
还有，建议增加线程选择功能，单线程测速更贴近观看油管实际水平
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: BigMango <notifications@github.com&gt;
发送时间: 2020年4月19日 20:51
收件人: BigMangos/speedtest-go-script <speedtest-go-script@noreply.github.com&gt;
抄送: netwlb <netwlb2009@gmail.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[BigMangos/speedtest-go-script] VPS重启完测试页面就打不开，要重装，不知是不是默认安装到/temp里头？ (#1)





 
在脚本中增加了 start 和 stop，系统重启后可以再次执行脚本中的 start 就可以了
