### ISSUE TITLE
请增加自定义测速线程选项

### ISSUE THREAD

**Issue by netwlb** [BigMangos/speedtest-go-script#2]
目前脚本里头默认下载是6线程，上传是3线程，希望能够增加自定义线程的选项，以贴近正常网页浏览（如YouTube、netflix、Instagram、Facebook等）的使用场景。谢谢大佬开发！！

**Comment by bigmangos** [comment]
目前脚本只是提供一键安装，测速线程选项需要修改原项目，请先参考原项目[Wiki](https://github.com/librespeed/speedtest/wiki)

**Comment by netwlb** [comment]
希望再增加一个自定义测速端口选项，默认不填则自动设为8989

**Comment by bigmangos** [comment]
@netwlb 这个可以，明天增加这个功能

**Comment by netwlb** [comment]
说增加就增加，太棒了
